### ISSUE TITLE
Can you provide your train_instructions.json?

### ISSUE THREAD

**Issue by gogoduan** [abyildirim/inst-inpaint#6]
I found that only the instructions of test are provided, can you further provide the larger data from training stage?

**Comment by abyildirim** [comment]
Training and validation instructions are generated using the **train_scenes.json** and **test_scenes.json** files in the dataset object. The reason for that is to generate different variants of instructions randomly using the object attributes and locations in the scene. On the other hand, we generated the fixed test instructions for each scene and provided them in **test_instructions.json** so that models can be compared as such there is no randomness.

**Comment by rrrchii** [comment]
Great work! Although some time has passed, I have a couple of questions after downloading and extracting the dataset:

It seems that the train_instructions file is missing. Is this expected?

I noticed that there are only 10,811 "remove" instructions in test_instructions.json, which is fewer than reported in the paper. Could you clarify this discrepancy?

Thank you! @abyildirim
